// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjawuriysacjfgstqjbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqYXd1cml5c2FjamZnc3RxamJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2OTM2NjEsImV4cCI6MjA2NTI2OTY2MX0.vPVH5aClJK6wKBVUSZ6V28nsV79eiVGLiusVZf6k_O4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);